'''
0) 
A number is a perfect square, or simply a square number, if it is the square of a positive integer.
For example, 25 is a square number because 5 x 5 = 25; and it is also an odd square.
Among the first 838,000 square numbers, what is the sum of all the odd squares?
'''

quadrados = [ i**2 for i in range(1,838001)]
soma = 0
for i in quadrados:
    if i % 2 == 1:
        soma += i
    
print(soma)

'''
1)
Find the sum of all the multiples of 3 or 5 below 1000.
''' 
soma = 0
for i in range(1000):
    if i % 3 == 0 or i % 5 == 0:
        soma += i

print(soma)

'''
2)
Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2
By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.
'''

f = 0
a = 1
b = 2
soma_par = b

while f <= 4000000:
    f = a + b
    if f % 2 == 0:
        soma_par += f
    a = b
    b = f 

print(soma_par)

'''
'''


